config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :posts do
    resources :comments, module: :posts
    resources :likes
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"

  def comments
    Comment.where(commentable: commentable, parent_id: id)
  end

  def destroy
    update(user: nil, body: nil)
  end

  def deleted?
    user.nil?
  end

  # Alternatively, we could move all the children to point to our parent instead

  #def child_comments
    #Comment.where(parent: self)
  #end

  #before_destroy :handle_children

  #def handle_children
    #child_comments.update_all(parent_id: parent_id)
  #end
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true
	has_attached_file :image, :styles => { :medium =>"300x300#", :thumb => "200x200#" }
  validates_attachment :image, content_type: { content_type:["image/jpg", "image/jpeg", "image/png"] }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :imageable, polymorphic: true

	has_attached_file :image, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
  	validates_attachment :image, content_type: { content_type:["image/jpg", "image/jpeg", "image/png"] }
end

app/models/post.rb
class Post < ApplicationRecord
	has_one :image, as: :imageable, dependent: :destroy
	accepts_nested_attributes_for :image
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @commentable }
        format.js
      end
    else
      redirect_to @commentable, alert: "Something went wrong"
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    redirect_to @commentable
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
  def create
    @post.likes.create(user_id: current_user.id)
    redirect_to post_path(@post)
  end
  private
  def find_post
    @post = Post.find_by(id: params[:post_id])
    if @post.nil?
    	flash[:alert] = 'Sorry, Record not found!'
    	redirect_to posts_path
    end
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Post.find_by(id: params[:post_id])
      if @commentable.nil?
      	redirect_to posts_path
      	flash[:alert] = 'Sorry, Record not found!'
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:image, :comments, :likes).all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if params[:comment]
      @comments = @post.comments.where(id: params[:comment])
    else
      @comments = @post.comments.where(parent_id: nil)
    end
    @user_post = current_user.posts.find_by(id: params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
    image = @post.build_image
  end

  # GET /posts/1/edit
  def edit
    image = @post.build_image
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.includes(:image, :comments, :likes).find_by(id: params[:id])
      if @post.nil?
        flash[:alert] = 'Sorry, Record is not found!'
        redirect_to posts_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, image_attributes: [:image, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def reply_to_comment_id(comment, nesting, max_nesting)
    # Use the comment as the parent if we allow unlimited nesting
    # or if it's inside the allowed nesting
    if max_nesting.blank? || nesting < max_nesting
      comment.id
    else
      # Otherwise, we want to use the comment's parent,
      # and just nest the new comment as a sibling
      comment.parent_id
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% nesting     = local_assigns.fetch(:nesting, 1) %>
<% max_nesting = local_assigns[:max_nesting] %>
<% continue_thread = local_assigns[:continue_thread] %>

<%= tag.div id: dom_id(comment), class: "border-left pl-4 mt-4" do %>
  <% if comment.deleted? %>
    <strong>[deleted]</strong> <%= link_to "posted", url_for(comment: comment.id, anchor: dom_id(comment)) %>
    <p>[deleted]</p>
  <% else %>
    <strong><%= comment.user.name %></strong> <%= link_to "posted", url_for(comment: comment.id, anchor: dom_id(comment)) %>
    <%= simple_format comment.body %>
  <% end %>

  <div data-controller="reply">
    <small>
      <%= link_to "Reply", "#", data: { action: "click->reply#toggle" } %>
      <%= link_to "Delete", [comment.commentable, comment], method: :delete, data: {confirm: "Are you sure?"} if comment.user == current_user %>
    </small>

    <%= render partial: "comments/form", locals: {
      commentable: comment.commentable,
      parent_id: reply_to_comment_id(comment, nesting, max_nesting),
      class: "mt-4 d-none",
      target: "reply.form"
    } %>
  </div>

  <%= tag.div id: "#{dom_id(comment)}_comments" do %>
    <% if continue_thread.present? && nesting >= continue_thread && comment.comments.any? %>
      <%= link_to "Continue this thread", url_for(comment: comment.id, anchor: dom_id(comment)) %>
    <% else %>
      <%= render comment.comments, continue_thread: continue_thread, nesting: nesting + 1, max_nesting: local_assigns[:max_nesting] %>
    <% end %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [commentable, Comment.new], html: { class: local_assigns[:class], data: { target: local_assigns[:target] } } do |form| %>
  <div class="form-group">
    <%= form.text_area :body, placeholder: "Add a comment", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :parent_id, value: local_assigns[:parent_id] %>
    <%= form.submit 'Comment', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.parent_id? %>
    var comments = document.querySelector("#<%= dom_id(@comment.parent) %>_comments")
<% else %>
    var comments = document.querySelector("#comments")
<% end %>

comments.insertAdjacentHTML('beforeend', '<%=j render partial: "comments/comment", locals: { comment: @comment }, format: :html %>')

var form = comments.parentElement.querySelector("form")
form.reset()

<% if @comment.parent_id? %>
  form.classList.add("d-none")
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Posts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarMain">
          <% if user_signed_in? %>
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item"><%= link_to "Posts", posts_path, class: "nav-link" %></li>
            </ul>
          <% end %>

          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <%= link_to posts_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
                <% end %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
                  <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= render 'shared/notices' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.fields_for :image do |image_form| %>
      <%= image_form.file_field :image, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/blogs_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= image_path post.image(:medium) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Posts</h1>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to new_post_path, class: 'btn btn-primary' do %>
      Add New Post
    <% end %>
  </div>
</div>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 blog-row">
      <div class="card text-center">
        <div class="picture">
          <%= image_tag post.image ? post.image.image.url(:thumb) : '' %>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= post.title %></h4>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></h4>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= post.comments.count %> <%= (post.comments.count) == 1 ? 'Comment' : 'Comments'%></h4>
        </div>
        <%= link_to "Show", post_path(post.id), class: "text-primary" %>
        <%= link_to "Delete", post_path(post.id), method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } if current_user.id == post.user_id %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if @user_post %>
  <div class="page-header">
    <%= link_to edit_post_path(@user_post), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
  </div>
<% end %>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @post.title %></dd>
  <dt>Image:</dt>
  <dd><%= image_tag @post.image ? @post.image.image.url(:thumb) : '' %></dd>
</dl>
<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<%= button_to 'Like', post_likes_path(@post), method: :post, class: "btn btn-primary", remote: true %>

<h3>Comments</h3>
<div id="comments">
  <%= render partial: "comments/form", locals: { commentable: @post } %>
  <% if params[:comment] %>
    <p>Single comment thread. <%= link_to "View all comments", url_for() %></p>
  <% end %>
  <%= render @comments, continue_thread: 5 %>
</div>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>